//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullTextSearch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FullTextSearch.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any other key to exit.
        /// </summary>
        internal static string AnyOtherKey {
            get {
                return ResourceManager.GetString("AnyOtherKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what would you like to do?.
        /// </summary>
        internal static string ChooseAction {
            get {
                return ResourceManager.GetString("ChooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose column you would like to update \n 1- news \n 2- heading.
        /// </summary>
        internal static string ChooseColumn {
            get {
                return ResourceManager.GetString("ChooseColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose CRUD operation.
        /// </summary>
        internal static string ChooseCRUD {
            get {
                return ResourceManager.GetString("ChooseCRUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what you want to do:\n 1- Create tables and indecis \n 2- Batch Insert.
        /// </summary>
        internal static string ChooseDBActions {
            get {
                return ResourceManager.GetString("ChooseDBActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the table you would like to perform CRUD Operations.
        /// </summary>
        internal static string ChooseTable {
            get {
                return ResourceManager.GetString("ChooseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record/Records has been created successfully..
        /// </summary>
        internal static string CreateRecord {
            get {
                return ResourceManager.GetString("CreateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully..
        /// </summary>
        internal static string DeletedRecord {
            get {
                return ResourceManager.GetString("DeletedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter record ID you would like to delete.
        /// </summary>
        internal static string EnterRecIdForDelete {
            get {
                return ResourceManager.GetString("EnterRecIdForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter record ID you would like to delete.
        /// </summary>
        internal static string EnterRecIdForUpdate {
            get {
                return ResourceManager.GetString("EnterRecIdForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text you would like to search:.
        /// </summary>
        internal static string EnterSearchText {
            get {
                return ResourceManager.GetString("EnterSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value for the _columnName_.
        /// </summary>
        internal static string EnterValueForCOlumn {
            get {
                return ResourceManager.GetString("EnterValueForCOlumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2- Go back to start screen.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- Initialize DB.
        /// </summary>
        internal static string InitializeDb {
            get {
                return ResourceManager.GetString("InitializeDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your selection is invalid..
        /// </summary>
        internal static string InvalidSelection {
            get {
                return ResourceManager.GetString("InvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2- Perform CRUD on data.
        /// </summary>
        internal static string PerformCRUD {
            get {
                return ResourceManager.GetString("PerformCRUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- Search another text.
        /// </summary>
        internal static string SearchMore {
            get {
                return ResourceManager.GetString("SearchMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3- Perform full text search on tables.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- Sports News.
        /// </summary>
        internal static string SportsTable {
            get {
                return ResourceManager.GetString("SportsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated successfully..
        /// </summary>
        internal static string UpdatedRecorded {
            get {
                return ResourceManager.GetString("UpdatedRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2- Weather News.
        /// </summary>
        internal static string WeatherTable {
            get {
                return ResourceManager.GetString("WeatherTable", resourceCulture);
            }
        }
    }
}
